// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuIuPTlNqsfv7dW9KReNOMr0ebAiPfRfw',
    appId: '1:1062608794290:web:260d9db8ff3f0f85c28fab',
    messagingSenderId: '1062608794290',
    projectId: 'flutter-fcm-cba29',
    authDomain: 'flutter-fcm-cba29.firebaseapp.com',
    storageBucket: 'flutter-fcm-cba29.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7yFHKpRiAKUTJXYfyPAzhoj6pTk7QNcM',
    appId: '1:1062608794290:android:7c324137f58e0f5bc28fab',
    messagingSenderId: '1062608794290',
    projectId: 'flutter-fcm-cba29',
    storageBucket: 'flutter-fcm-cba29.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJPBKIE65_AZSqgoh25F5K9_gnBw5EjZE',
    appId: '1:1062608794290:ios:78b5056b822c5331c28fab',
    messagingSenderId: '1062608794290',
    projectId: 'flutter-fcm-cba29',
    storageBucket: 'flutter-fcm-cba29.appspot.com',
    iosClientId:
        '1062608794290-qc4essq3ndsj1hqio33781p2fj1u5qvg.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFcm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJPBKIE65_AZSqgoh25F5K9_gnBw5EjZE',
    appId: '1:1062608794290:ios:78b5056b822c5331c28fab',
    messagingSenderId: '1062608794290',
    projectId: 'flutter-fcm-cba29',
    storageBucket: 'flutter-fcm-cba29.appspot.com',
    iosClientId:
        '1062608794290-qc4essq3ndsj1hqio33781p2fj1u5qvg.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFcm',
  );
}
